/* ACTION TYPE CONSTANTS
You can use any convention you wish here,
but the name should remain UPPER_SNAKE_CASE for consistency.
*/
const createActionName = name => `appointments/duck/${name}`;

const FETCH_APPOINTMENTS_BY_YEAR = createActionName('FETCH_APPOINTMENTS_BY_YEAR');
const FETCH_APPOINTMENTS_BY_YEAR_SUCCESS = createActionName('FETCH_APPOINTMENTS_BY_YEAR_SUCCESS');
const FETCH_APPOINTMENTS_BY_YEAR_FAILURE = createActionName('FETCH_APPOINTMENTS_BY_YEAR_FAILURE');
const FETCH_APPOINTMENTS_REPORT = createActionName('FETCH_APPOINTMENTS_REPORT');
const FETCH_APPOINTMENTS_REPORT_SUCCESS = createActionName('FETCH_APPOINTMENTS_REPORT_SUCCESS');
const CLEAR_APPOINTMENTS_REPORT_CACHE = createActionName('CLEAR_APPOINTMENTS_REPORT_CACHE');
const FETCH_REPORT_PARAMS = createActionName('FETCH_REPORT_PARAMS');
const FETCH_REPORT_PARAMS_SUCCESS = createActionName('FETCH_REPORT_PARAMS_SUCCESS');
const FETCH_APPOINTMENTS_REPORT_FAILURE = createActionName('FETCH_APPOINTMENTS_REPORT_FAILURE');
const FETCH_APPOINTMENTS_DATA = createActionName('FETCH_APPOINTMENTS_DATA');
const FETCH_APPOINTMENTS_DATA_SUCCESS = createActionName('FETCH_APPOINTMENTS_DATA_SUCCESS');
const FETCH_APPOINTMENTS_DATA_FAILURE = createActionName('FETCH_APPOINTMENTS_DATA_FAILURE');
const FETCH_UPDATE_APPOINTMENT = createActionName('FETCH_UPDATE_APPOINTMENT');
const FETCH_UPDATE_APPOINTMENT_SUCCESS = createActionName('FETCH_UPDATE_APPOINTMENT_SUCCESS');
const FETCH_UPDATE_BLURRED_APPOINTMENT = createActionName('FETCH_UPDATE_BLURRED_APPOINTMENT');
const FETCH_UPDATE_BLURRED_APPOINTMENT_SUCCESS = createActionName('FETCH_UPDATE_BLURRED_APPOINTMENT_SUCCESS');
const FETCH_UPDATE_APPOINTMENT_FAILURE = createActionName('FETCH_UPDATE_APPOINTMENT_FAILURE');
const START_APPOINTMENT_EDIT_MODE = createActionName('START_APPOINTMENT_EDIT_MODE');
const CLEAR_APPOINTMENT_EDIT_MODE = createActionName('CLEAR_APPOINTMENT_EDIT_MODE');
const FETCH_USER_FEEDBACKS_SUCCESS = createActionName('FETCH_USER_FEEDBACKS_SUCCESS');
const FETCH_ADMIN_FEEDBACKS_SUCCESS = createActionName('FETCH_ADMIN_FEEDBACKS_SUCCESS');
const FETCH_CREATE_FEEDBACK_SUCCESS = createActionName('FETCH_CREATE_FEEDBACK_SUCCESS');
const FETCH_UPDATE_FEEDBACK_SUCCESS = createActionName('FETCH_UPDATE_FEEDBACK_SUCCESS');
const COPY_APPOINTMENT_DATA = createActionName('COPY_APPOINTMENT_DATA');
const PASTE_APPOINTMENT_DATA = createActionName('PASTE_APPOINTMENT_DATA');

export {
  FETCH_APPOINTMENTS_BY_YEAR,
  FETCH_APPOINTMENTS_BY_YEAR_SUCCESS,
  FETCH_APPOINTMENTS_BY_YEAR_FAILURE,
  FETCH_APPOINTMENTS_REPORT,
  FETCH_APPOINTMENTS_REPORT_SUCCESS,
  CLEAR_APPOINTMENTS_REPORT_CACHE,
  FETCH_REPORT_PARAMS,
  FETCH_REPORT_PARAMS_SUCCESS,
  FETCH_APPOINTMENTS_REPORT_FAILURE,
  FETCH_APPOINTMENTS_DATA,
  FETCH_APPOINTMENTS_DATA_SUCCESS,
  FETCH_APPOINTMENTS_DATA_FAILURE,
  FETCH_UPDATE_APPOINTMENT,
  FETCH_UPDATE_APPOINTMENT_SUCCESS,
  FETCH_UPDATE_BLURRED_APPOINTMENT,
  FETCH_UPDATE_BLURRED_APPOINTMENT_SUCCESS,
  FETCH_UPDATE_APPOINTMENT_FAILURE,
  START_APPOINTMENT_EDIT_MODE,
  CLEAR_APPOINTMENT_EDIT_MODE,
  FETCH_USER_FEEDBACKS_SUCCESS,
  FETCH_CREATE_FEEDBACK_SUCCESS,
  FETCH_ADMIN_FEEDBACKS_SUCCESS,
  FETCH_UPDATE_FEEDBACK_SUCCESS,
  COPY_APPOINTMENT_DATA,
  PASTE_APPOINTMENT_DATA,
};
